### ISSUE TITLE
Form react helper wouldn't update inner components

### ISSUE THREAD

**Issue by evgeniedasaev** [TinkoffCreditSystems/stapp#26] opened 2018-07-12 20:29 UTC
**Problem**
For rendering some content based on upper component props we can't use components wrapped in Form helper.
For example:
```
const Form = createForm(app);

const SomeStatelessComponent = ({ fields }) => <Form>
{
   ({ handleSubmit }) => <form onSubmit={handleSubmit}>
         {   fields.map(renderField)   }

         <button onClick={handleSubmit}>OK</button>
    </form>
}
```

If fields was updated ```fields.map(renderField)``` wouldn't be called. But if something included in ```formSelector``` was changed form would be re-rendered.

**Solution**
Add "extra" selector which extends ```formSelector```
Mb something else

**Comment by dmitry-korolev** [comment] 2018-07-16 08:53
Confirmed
https://codesandbox.io/s/w29v1kvxj7

Will be fixed in 2.0.0 release.

**Comment by dmitry-korolev** [comment] 2018-07-16 12:01
Actually, are we sure that this should be fixed?

**Comment by dmitry-korolev** [comment] 2018-08-12 20:08
@evgeniedasaev @berezinmv ^

**Comment by dmitry-korolev** [comment] 2018-09-06 16:35
Irrelevant since 2.3.0.
We introduced other problems though 😆

**Closed by dmitry-korolev** 2018-09-06 16:35 UTC
Labels: RFC, stapp-react
